language: go

go:
  - 1.x
  - 1.6
  - 1.7.x
  - 1.8.x

before_install:
  - go get -t -v ./...

install:
  - go get github.com/haya14busa/goverage

script:
  - goverage -coverprofile=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)

